name: Send a message to parent repos automactially

on:
  workflow_dispatch:
  push:
    branchs: [main]
    
jobs:
  send-parent-repo-message:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repos
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.YDM_TOKEN }}
            
      - name: send a POST request to the GitHub API
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.YDM_TOKEN }}" \
          --data '{"event_type": "update-submodules"}' \
          https://api.github.com/repos/longavailable/ydm-climate/dispatches
